### ISSUE TITLE
DllNotFoundException on Android

### ISSUE THREAD

**Issue by aloisdeniel** [xamarin/flex#18]
Hello,

I currently have an issue with the flex library referenced from an Android project.

I get this exception (the lack of a native dll) everytime a launch my app (on a *Huawei P9 Light*).
```
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.DllNotFoundException: flex
[MonoDroid]   at (wrapper managed-to-native) Xamarin.Flex.NativeFunctions:flex_item_new ()
[MonoDroid]   at Xamarin.Flex.Item..ctor () [0x0001f] in <2305ceba69ca44189b39054f10c03dff>:0 
[MonoDroid]   at Flexml.Layout+Item..ctor () [0x00000] in <ae81aa72541a485caa4eba5869d56bcd>:0 
[MonoDroid]   at Flexml.Samples.Droid.TestLayout..ctor () [0x00006] in <cf7fd16d2e27406c9b481914a0e7aee9>:0 
[MonoDroid]   at Flexml.Samples.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00007] in <cf7fd16d2e27406c9b481914a0e7aee9>:0 
[MonoDroid]   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <105eb6af5a67424c92a9db1727761fb6>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object:66d14ac8-0fa9-4bd2-9d0d-5952e390f6c3 (intptr,intptr,intptr)
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
```

Any workaround ?

**Comment by aloisdeniel** [comment]
This is probably caused by the default `armeabi-v7a` ABI in the csproj which don't have any native library.

![image](https://user-images.githubusercontent.com/7687231/32543463-fdee6f94-c475-11e7-8356-846235192c93.png)

![image](https://user-images.githubusercontent.com/7687231/32543475-068e0772-c476-11e7-82c9-8e5776700b64.png)

**Comment by lrz** [comment]
Thanks for reporting this, I will make sure we deliver a slice for this architecture in the next release.

**Comment by lrz** [comment]
Hi @aloisdeniel I just pushed a new version of the nuget with the missing architecture, would you mind to give it a try and let me know if things are better now? I wasn't able to test here but it should work :) https://www.nuget.org/packages/Xamarin.Flex/0.3.2

**Comment by aloisdeniel** [comment]
It is working fine now! Thanks @lrz.
