### ISSUE TITLE
iOS lib should be a framework

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/flex#35]
so it works without any changes with the previewer

**Comment by lrz** [comment]
Support for this has just been added (following what UrhoShark is doing). As of 8d6322c2c58dc0997d98d86055f4874891c21d09 we are now building a flex.framework bundle + a .zip copy of it, and as of 629d4f5ff68cbee970893fe274b6b84cd94714d0 we copy the .zip file inside the nuget.

From what I understand It looks like Xamarin should autodetect and load the zipped framework file as is, but I will have to test this.
