### ISSUE TITLE
test_grow9: for parent->child position propagation

### ISSUE THREAD

**Issue by deepfire** [xamarin/flex#38]
PR https://github.com/xamarin/flex/pull/37 adds a failing test.  I'm not sure if that's expected -- it doesn't seem so for me, though -- but maybe I misunderstand something:

```
test_grow9 (test_grow.c:232): failed test `flex_item_get_frame_y(_item) == 50.0' (is 0.0)
test_grow9 (test_grow.c:233): failed test `flex_item_get_frame_y(_item) == 50.0' (is 0.0)
```

To me, this looks like, while the position of the second intermediate node (`child2`) is computed properly, it fails to be propagated to its children (`child21`, `child22`).

**Comment by deepfire** [comment]
.and then I see test_children4, and I realize that children coordinates are probably parent-relative.

**Comment by lrz** [comment]
Ah yes they are, sorry about the confusion!
