### ISSUE TITLE
MaxWidth / MaxHeight Missing

### ISSUE THREAD

**Issue by brettclutch** [xamarin/flex#40]
I don't know if this is part of the flexbox spec or not but I'm porting from Yoga and find these missing. I thought about just implementing myself but that is not easily possible on my end since its not just a simple Math.Max in a Width/Height property setter, as you want the MaxWidth/MaxHeight to be active during the layout calculations. 

If I end up implementing this myself will you be taking pull requests?

**Comment by brettclutch** [comment]
I will close this for now since I now realize I needed to investigate Item.Shrink = 0 and Item.Grow = 0 in combination with a Width = Height.

**Comment by lrz** [comment]
We will be considering any pull requests you might open!
