### ISSUE TITLE
Setting only Width/Height on Item results in FrameWidth/FrameHeight being 0

### ISSUE THREAD

**Issue by brettclutch** [xamarin/flex#41]
[FlexBugReport.zip](https://github.com/xamarin/flex/files/1757268/FlexBugReport.zip)

Attached is source code example containing these simple lines where I don't get any width/height in FrameWidth/Heigth as I expect on the top level root 'Item' (Item with no parent). Can you please take a look (please advise if I'm doing something wrong or have an incorrect assumption). Thanks. 

`
Item rootItem = new Item();
rootItem.Width = 800;
rootItem.Height = 800;

rootItem.Layout();

Console.WriteLine($"Frame Height: {rootItem.FrameHeight}, Frame Width: {rootItem.FrameWidth}");
Console.ReadLine();
`

Outputs: Frame Height: 0, Frame Width: 0

**Comment by brettclutch** [comment]
Any feedback on that issue? Sorry to be a bother but I can't pull off the curb since this is a core blocker to even using the library since I can never assign the root node any height / width of which to start any layout calculations.

**Comment by lrz** [comment]
Sorry we don't have feedback at this point. We will consider this issue, you can also submit a pull request with a proper fix if you make one.

**Comment by brettclutch** [comment]
That's ok, since I couldn't pull off the curb I switched back to Facebook yoga. Thanks for the effort on the library share.
